### ISSUE TITLE
Troque sua Senha

### ISSUE THREAD

**Issue by Marii-brito** [PetJournal/petjournal.web#8]
Definição:

Como usuário, quero criar minha nova senha para poder ter acesso ao aplicativo.

Descrição:

Nessas telas o objetivo é que o usuário consiga recuperar a senha caso ele tenha perdido ou esquecido. E para isso ele deverá passar por três processos: enviar o código de recuperação para o email ~ou telefone~, digitar o código recebido e criar uma senha nova. 
Se esses ~três~ dois passos forem feitos, o usuário poderá ter acesso ao aplicativo novamente.

*Obs: Fluxo de recuperação de senha foi alterado na US, após começo da Sprint. Para a primeira versão, não teremos mais a opção do usuário recuperar a senha através do SMS, somente recuperação de senha por e-mail.*

[Protótipo Figma - Troque sua Senha](https://www.figma.com/proto/ynvraEWObyi5rxueisWlPs/Telas-Pet-Journal?node-id=586-1013&scaling=min-zoom&page-id=564%3A835&starting-point-node-id=586%3A996)

![Image](https://user-images.githubusercontent.com/129445779/232587325-9f9aa1c6-8a9a-4fc8-8fa4-433b1bb76bbf.png)

Critérios de Aceite:

> O campo Senha deve ser obrigatório e conter no mínimo 8 caracteres alfanuméricos e especiais e deverá aparecer a seguinte mensagem:

> A senha deve ter pelo menos 8 caracteres. Para torná-la mais forte, use letras maiúsculas e minúsculas, números e símbolos como ! @ # $ % & * =

> Se o sistema, após clicar em “Redefinir senha” verificar que senha não atinge os requisitos necessários, deverá aparecer a seguinte mensagem:

 “ A senha informada não atende os requisitos necessários de 8 caracteres"

> Quando o usuário estiver colocando a senhas e optar por não visualizar a senha, a mesma deverá ser apresentada através de “********”.

> Quando o usuário estiver colocando a senha ele deverá ser capaz de visualizar a senha caso ele clique na opção “Mostrar” no campo “Senha”.

> O campo “Confirmar Senha” deve ser igual ao campo “Senha”.

> Se o sistema, após o clique em “Redefinir senha” verificar que as duas senhas  não são idênticas, uma mensagem de aviso deve ser apresentada na tela: 

`“As senhas devem ser idênticas"`

> Se o sistema, após o clique em “Redefinir senha” verificar que as duas senhas são idênticas, uma mensagem “Redefinição de senha concluída com sucesso” deverá aparecer na tela e em seguida ser redirecionado para tela de login. [US Login](https://docs.google.com/document/d/1DxyuuWQNUpeOZWZ31JcAZm38ontHlXNh/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)

Associações:

[Login](https://docs.google.com/document/d/1DxyuuWQNUpeOZWZ31JcAZm38ontHlXNh/edit?usp=sharing&ouid=105032028308354704003&rtpof=true&sd=true)

**Comment by larissaOliveiraz** [comment]
## Tasks
### Layout
- [x] Campo de senha
- [x] Campo de confirmar senha
- [x] Botão de "Mostrar" e "Ocultar" a senha 
- [x] Checkbox de acesso a conta com a nova senha
- [x] Botão "Redefinir senha" que leva o usuário para a tela de login  

### Validação
- [x] Valida se os campos estão preenchidos
- [x] Valida se a senha preenche os requisitos necessários de 8 caracteres, com maiúsculas, minúsculas, números e símbolos
- [x] Valida se o valor digitado nos dois campos são iguais
- [x] Se o usuário preencher os campos incorretamente são exibidas as mensagens de erro
- [x] O botão "Redefinir senha" fica desabilitado até que o usuário preencha os campos corretamente
